teststack = Stack([1, 2, 3, 4, 5])
popstack1 = teststack.offload()
print(popstack1)
stacktest(popstack1, 1)
popstack2 = teststack.offload()
stacktest(popstack2, 2)
print(teststack.offload())
print(teststack.offload())
print(teststack.offload())
emptylisttest(teststack.list)
teststack.stacking(1)
popstack3 = teststack.offload()
stacktest(popstack3, 1)
emptylisttest(teststack.list)